# Generated by Django 4.0.4 on 2022-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=60, null=True)),
                ('title', models.CharField(max_length=255)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('acquired', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(related_name='book_authors', to='books.author')),
            ],
        ),
    ]
